language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - cmake
      - check

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - make test
after_success:
  - cd ..
  - coveralls --exclude tests --exclude libs
