language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - cmake
      - check

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - make test
