language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - cmake
      - check
  sonarcloud:
    organization: "fexolm-github"
before_install:
  - pip install --user cpp-coveralls
script:
  - mkdir build
  - cd build
  - cmake .. && make && make test && cd .. && sonar-scanner
after_success:
  - coveralls --exclude tests --exclude libs
